import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookieToInitialState } from "wagmi";
import { headers } from "next/headers";
import WagmiProviderComp from "@/config/wagmi-provider";

import "./globals.css";
import { config } from "@/config/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WagmiProviderComp initialState={initialState}>
          <main>
            {children}
          </main>
        </WagmiProviderComp>
      </body>
    </html>
  );
}
